env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/joaodrp/gelf-pretty
  description: CLI to pretty-print Graylog Extended Log Format (GELF) log lines.
  maintainer: João Pereira
  license: MIT
  formats:
    - deb
    - rpm
  dependencies:
    - git
  recommends:
    - rpm
snapcraft:
  summary: CLI to pretty-print GELF log lines
  description: CLI to pretty-print Graylog Extended Log Format (GELF) log lines.
  grade: stable
  confinement: strict
  publish: true
brew:
  github:
    owner: joaodrp
    name: homebrew-tap
  homepage:  https://github.com/joaodrp/gelf-pretty
  description: CLI to pretty-print Graylog Extended Log Format (GELF) log lines
  test: system "#{bin}/gelf-pretty --version"
  skip_upload: auto
release:
  prerelease: auto
  draft: true
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^style:'
      - Merge pull request
      - Merge branch
