dist: xenial
language: go
addons:
  apt:
    packages:
      - rpm
      - snapd
go:
  - 1.12.x
  # - tip
env:
  - GO111MODULE=on
  - PATH=/snap/bin:$PATH
install:
  - make setup
  - sudo snap install snapcraft --classic
script: make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo $SNAP_TOKEN | snapcraft login --with -
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
notifications:
  email: false
